name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # Executa para qualquer tag que comece com 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          TAG_NAME=${{ github.ref }}
          # Extrai o nome da tag removendo 'refs/tags/'
          TAG_NAME=${TAG_NAME#refs/tags/}
          docker build -t ederbraga/calculadora:${TAG_NAME} .

      - name: Push Docker image
        run: |
          TAG_NAME=${{ github.ref }}
          TAG_NAME=${TAG_NAME#refs/tags/}
          docker push ederbraga/calculadora:${TAG_NAME}
