name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # Executa para qualquer tag que comece com 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          TAG_NAME=${{ github.ref }}
          # Extrai o nome da tag removendo 'refs/tags/'
          TAG_NAME=${TAG_NAME#refs/tags/}
          docker build -t ederbraga/calculadora:${TAG_NAME} .

      - name: Push Docker image
        run: |
          TAG_NAME=${{ github.ref }}
          TAG_NAME=${TAG_NAME#refs/tags/}
          docker push ederbraga/calculadora:${TAG_NAME}

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Faça login no Heroku
          echo "machine api.heroku.com" >> ~/.netrc
          echo "  login ${{ secrets.HEROKU_USERNAME }}" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login ${{ secrets.HEROKU_USERNAME }}" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc

          # Configure a stack do Heroku para container
          heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}

          # Taguear a imagem para o Heroku
          TAG_NAME=${{ github.ref }}
          TAG_NAME=${TAG_NAME#refs/tags/}
          docker tag ederbraga/calculadora:${TAG_NAME} registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

          # Fazer o push da imagem para o Heroku
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

          # Liberar o container
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
